# Generated by Django 4.1.4 on 2023-12-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
